### ISSUE TITLE
Dynet版本问题

### ISSUE THREAD

**Issue by aaronlyt** [jcyk/greedyCWS#2]
请问使用的Dynet版本是多少？

Traceback (most recent call last):
  File "train.py", line 28, in <module>
    word_proportion= 0.5
  File "/home/lyt/workspace/CWS/greedyCWS-master/src/model.py", line 187, in dy_train_model
    cws = CWS(Cemb,character_idx_map,options)
  File "/home/lyt/workspace/CWS/greedyCWS-master/src/model.py", line 18, in __init__
    self.trainer = dy.MomentumSGDTrainer(model,options['lr'],options['momentum'],options['edecay']) # we use Momentum SGD
  File "_dynet.pyx", line 5878, in _dynet.MomentumSGDTrainer.__cinit__
TypeError: __cinit__() takes at most 3 positional arguments (4 given)

**Comment by xiaozhewen** [comment]
作者使用的估计是V1.0或者V1.1，[版本](https://github.com/clab/dynet/releases)
我试着装这两个版本，但总是安装不成功。
使用较新版本的话，去掉edecay参数self.trainer = dy.MomentumSGDTrainer(model,options['lr'],options['momentum']） 后面也需要做些小改动就可以

**Comment by jcyk** [comment]
You can download the Dynet repository at earlier point (before when this repo was published) in [its history](https://github.com/clab/dynet/commits/master).

**Comment by xiaozhewen** [comment]
@jcyk 作者你好，我在重现结果时遇到了一些问题。
论文源码（未修改）

> cws.trainer.update_epoch(1.)
        end_time = time.time()
        print 'Trained %s epoch(s) (%d samples) took %.lfs per epoch'%(eidx+1,nsamples,(end_time-start_time)/(eidx+1))       
        test(cws,dev_file,'../result/dev_result%d'%(eidx+1))
        os.system('python score.py %s %d %d'%(dev_file,eidx+1,eidx+1))
        cws.save('epoch%d'%(eidx+1))
        print 'Current model saved'
按照README.md 运行代码，测试PKU，F1值95.1

> [***@gpu01 src]$ ./score ../data/pku_train ../data/pku_test ../result/dev/dev_result28 > ../../result/score/greedy_pku_test_seg.utf8
[***@gpu01 src]$ tail -n 14 ../../result/score/greedy_pku_test_seg.utf8
=== SUMMARY:
=== TOTAL INSERTIONS:   1766
=== TOTAL DELETIONS:    1496
=== TOTAL SUBSTITUTIONS:        3477
=== TOTAL NCHANGE:      6739
=== TOTAL TRUE WORD COUNT:      104371
=== TOTAL TEST WORD COUNT:      104641
=== TOTAL TRUE WORDS RECALL:    0.952
=== TOTAL TEST WORDS PRECISION: 0.950
**=== F MEASURE:  0.951**
=== OOV Rate:   0.927
=== OOV Recall Rate:    0.950
=== IV Recall Rate:     0.988
    ../result/dev/dev_result28      1766    1496    3477    6739    104371  104641  0.952   0.950   0.951   0.927      0.950   0.988

1、但是，test(cws,dev_file,'../result/dev_result%d'%(eidx+1))，测试文件dev_file是../data/pku_test文件，这个**pku_test是已经分词的**，test函数输出**分词结果**保存为../result/dev_result%d'%(eidx+1)，然后运行score评分脚本，=== F MEASURE:  0.951 是**分词结果**和**pku_test**对比得出。

2、**分词结果**和**标准分割icwb2-data/gold/pku_test_gold.utf8** 对比=== F MEASURE:  0.843

3、运行test模式，load最好的模型，测试文件为未分词的icwb2-data/testing/pku_test.utf8，得出的分词结果和**标准分割icwb2-data/gold/pku_test_gold.utf8**对比是F值是79。

这是我疑惑的地方，是不是1中得出的评分结果有失偏颇，因为一是使用**已分词的文本pku_test**做测试，二是使用这个已分词文本作为标准分割。

很想和你详聊，不介意的话加下我QQ可好：928371104     本人小白一枚，若有错误还请担待
