### ISSUE TITLE
实验结果的一些疑问

### ISSUE THREAD

**Issue by xiaozhewen** [jcyk/greedyCWS#3]
在重现PKU测试文本实验结果时，遇到下列问题：
论文源码（未修改）

> cws.trainer.update_epoch(1.)
        end_time = time.time()
        print 'Trained %s epoch(s) (%d samples) took %.lfs per epoch'%(eidx+1,nsamples,(end_time-start_time)/(eidx+1))       
        test(cws,dev_file,'../result/dev_result%d'%(eidx+1))
        os.system('python score.py %s %d %d'%(dev_file,eidx+1,eidx+1))
        cws.save('epoch%d'%(eidx+1))
        print 'Current model saved'
按照README.md 运行代码，测试PKU，F1值95.1

> [***@gpu01 src]$ ./score ../data/pku_train ../data/pku_test ../result/dev/dev_result28 > ../../result/score/greedy_pku_test_seg.utf8
[***@gpu01 src]$ tail -n 14 ../../result/score/greedy_pku_test_seg.utf8
=== SUMMARY:
=== TOTAL INSERTIONS:   1766
=== TOTAL DELETIONS:    1496
=== TOTAL SUBSTITUTIONS:        3477
=== TOTAL NCHANGE:      6739
=== TOTAL TRUE WORD COUNT:      104371
=== TOTAL TEST WORD COUNT:      104641
=== TOTAL TRUE WORDS RECALL:    0.952
=== TOTAL TEST WORDS PRECISION: 0.950
**=== F MEASURE:  0.951**
=== OOV Rate:   0.927
=== OOV Recall Rate:    0.950
=== IV Recall Rate:     0.988
    ../result/dev/dev_result28      1766    1496    3477    6739    104371  104641  0.952   0.950   0.951   0.927      0.950   0.988

1、但是，test(cws,dev_file,'../result/dev_result%d'%(eidx+1))，测试文件dev_file是../data/pku_test文件，这个**pku_test是已经分词的**，test函数输出**分词结果**保存为../result/dev_result%d'%(eidx+1)，然后运行score评分脚本，=== F MEASURE:  0.951 是**分词结果**和**pku_test**对比得出。

2、**分词结果**和**标准分割icwb2-data/gold/pku_test_gold.utf8** 对比=== F MEASURE:  0.843

3、运行test模式，load最好的模型，测试文件为未分词的icwb2-data/testing/pku_test.utf8，得出的分词结果和**标准分割icwb2-data/gold/pku_test_gold.utf8**对比是F值是79。

这是我疑惑的地方，是不是1中得出的评分结果有失偏颇，因为一是使用**已分词的文本pku_test**做测试，二是使用这个已分词文本作为标准分割。

小白一枚，如有问题，多多包涵

**Comment by hotchilipowder** [comment]
可能是预处理的问题，因为预处理将英语和数字进行了替换操作。
Because it uses preprocess.py to do some preprocesses, and replace the english and number.
```
rNUM = u'(-|\+)?\d+((\.|·)\d+)?%?'
rENG = u'[A-Za-z_.]+'
```
因此你直接用源数据对比效果是不够
SO, you use the icwb2-data/gold/pku_test_gold.utf8 will get different resutls.

**Comment by jcyk** [comment]
@xiaozhewen 
我们对数字，字母和标点做了预处理。详见论文和preprocess.py
